#pragma once

#define ENABLE_RGB_MATRIX_JACEFRIO                    // MY CUSTOM ANIMATION BABY
#define ENABLE_RGB_MATRIX_JACEFRIO_COLDMAP            // MY CUSTOM ANIMATION BABY
#define ENABLE_RGB_MATRIX_JACEFRIO_HEATMAP            // MY CUSTOM ANIMATION BABY
#define ENABLE_RGB_MATRIX_JACEFRIO_LIGHTMAP           // MY CUSTOM ANIMATION BABY
#define ENABLE_RGB_MATRIX_JACEFRIO_MATH_WAVE          // MY CUSTOM ANIMATION BABY
#define ENABLE_RGB_MATRIX_JACEFRIO_TWOCOLOR_WAVE      // MY CUSTOM ANIMATION BABY
#define ENABLE_RGB_MATRIX_JACEFRIO_WAVE               // MY CUSTOM ANIMATION BABY
#define ENABLE_RGB_MATRIX_JACEFRIO_BREATHINGCYCLE     // MY CUSTOM ANIMATION BABY
#define ENABLE_RGB_MATRIX_JACEFRIO_FLOW               // MY CUSTOM ANIMATION BABY
#define ENABLE_RGB_MATRIX_JACEFRIO_TEST               // MY CUSTOM ANIMATION BABY
#define ENABLE_RGB_MATRIX_FIRE                        // Dave's Garage Tutorial + My Code
#define ENABLE_RGB_MATRIX_FLOWER_BLOOMING             // Animation from Github
#define ENABLE_RGB_MATRIX_KITT                        // Animation from Github`